export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SHOW_UPDATE_MODAL = "SHOW_UPDATE_MODAL";
export const SHOW_ALERT_MODAL = "SHOW_ALERT_MODAL";
export const UPDATE_MODAL_CLOSE = "UPDATE_MODAL_CLOSE";
export const ALERT_MODAL_CLOSE = "ALERT_MODAL_CLOSE";
